apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: test/images/gameserver
      context: test/images/gameserver
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - k8s/fleet.yaml
